services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=soduh
      - MONGO_INITDB_ROOT_PASSWORD=soduh
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=soduh
      - ME_CONFIG_MONGODB_ADMINPASSWORD=soduh
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo: {}